issue fixes mostly on form-views
hackuci/HackUCI-Site pull request #97
Opened 2020-12-09 01:55 UTC by nathan-tang

// I think i can close these:
Issue #74
Issue #80
Issue #66
Issue #62
Issue #85
Issue #60
Issue #71
Issue #47
Issue #53
Issue #69
Issue #19

// iffy ones that will probably leave open for now
Issue #84 (sorta? I added a line break then deleted it but it fixed it???)
Issue #70 && Issue #48 (sizing is weird between different monitors probably will have to test this more)

2020-12-09 02:23 UTC, zpinto requested changes
just change the ternary statements for making select items white and I think everything else is good

2020-12-09 02:23 UTC, zpinto commented on app/client/src/app/components/form-components/educationalInfo.js
> +                (values.pronouns !== undefined
shouldn't this be value.major

2020-12-09 02:23 UTC, zpinto commented on app/client/src/app/components/form-components/educationalInfo.js
> +                (values.pronouns !== undefined
value.graduationYear

2020-12-09 20:06 UTC, zpinto commented
The application form is not wide enough

<img width="1000" alt="Screen Shot 2020-12-09 at 12 05 27 PM" src="https://user-images.githubusercontent.com/20071182/101681418-f63fcd00-3a16-11eb-8e60-dbb491fd818b.png">

2020-12-09 23:05 UTC, nathan-tang commented
latest commit addresses Issue #23 , no longer need to remove TODO as there should be no cases it is empty now.

2020-12-11 07:49 UTC, zpinto approved these changes
Nice job on this PR. You hit a bunch of issues 👍 I was able to figure out what was causing /application to not load and fixed it.

2020-12-11 07:49 UTC, merged